//! Platform-aware resolution of the bundled `rathole` binary + config.
//!
//! `rathole` is a platform-specific native binary (macOS arm64 `.bin`,
//! Windows `.exe`, …). The serve binary ships with a `rathole/` bundle at
//! the project root that separates binaries per platform:
//!
//! ```text
//! rathole/
//! ├── bin/
//! │   ├── macos/rathole      # macOS (aarch64-apple-darwin)
//! │   └── windows/rathole.exe # Windows (x86_64-pc-windows-msvc)
//! └── settings/*.toml         # tunnel configs (33-/40-/41- prefix)
//! ```
//!
//! The default path is chosen at compile time via [`std::env::consts::OS`],
//! so a macOS build resolves the macOS binary and a Windows build resolves
//! `rathole.exe` — no runtime platform sniffing needed. Both defaults can be
//! overridden at runtime with the `RATHOLE_BIN` / `RATHOLE_CONFIG`
//! environment variables (see [`default_bin`] / [`default_config`]).

/// Subdirectory of `rathole/bin/` holding this platform's binary.
#[cfg(target_os = "windows")]
const PLATFORM_DIR: &str = "windows";
#[cfg(target_os = "macos")]
const PLATFORM_DIR: &str = "macos";
#[cfg(target_os = "linux")]
const PLATFORM_DIR: &str = "linux";
#[cfg(not(any(target_os = "windows", target_os = "macos", target_os = "linux")))]
const PLATFORM_DIR: &str = "unknown";

/// Binary file name on this platform (Windows appends `.exe`).
#[cfg(target_os = "windows")]
const BIN_NAME: &str = "rathole.exe";
#[cfg(not(target_os = "windows"))]
const BIN_NAME: &str = "rathole";

/// Default tunnel config (generated by the settings panel, see
/// [`crate::config::RATHOLE_CONFIG_FILE`]).
const DEFAULT_CONFIG: &str = crate::config::RATHOLE_CONFIG_FILE;

/// Resolve the rathole binary path for the current platform.
///
/// Precedence:
/// 1. `RATHOLE_BIN` env var (absolute or CWD-relative, used verbatim).
/// 2. `rathole/bin/<os>/<binary>` relative to the current working directory.
/// 3. Search upward from the running executable for `rathole/bin/<os>/<binary>`
///    (covers `cargo run`, `target/{debug,release}/…`, and running the binary
///    from an arbitrary CWD).
#[must_use]
pub fn default_bin() -> String {
    if let Ok(v) = std::env::var("RATHOLE_BIN") {
        return v;
    }
    resolve_bundled(&format!("rathole/bin/{PLATFORM_DIR}/{BIN_NAME}"))
}

/// Resolve the rathole tunnel config path.
///
/// Precedence: `RATHOLE_CONFIG` env var, then the bundled
/// `rathole/settings/33-9464.toml` (CWD first, then upward from the executable).
#[must_use]
pub fn default_config() -> String {
    if let Ok(v) = std::env::var("RATHOLE_CONFIG") {
        return v;
    }
    resolve_bundled(DEFAULT_CONFIG)
}

/// Locate a bundled file first relative to the CWD, then by walking up from
/// the running executable's directory. Falls back to the CWD-relative path
/// (so the caller can report a meaningful "not found" error later).
fn resolve_bundled(relative: &str) -> String {
    if std::path::Path::new(relative).exists() {
        return relative.to_string();
    }
    if let Ok(exe) = std::env::current_exe() {
        for ancestor in exe.ancestors().skip(1).take(5) {
            let candidate = ancestor.join(relative);
            if candidate.exists() {
                return candidate.to_string_lossy().into_owned();
            }
        }
    }
    relative.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bin_name_matches_platform() {
        if cfg!(target_os = "windows") {
            assert_eq!(BIN_NAME, "rathole.exe");
        } else {
            assert_eq!(BIN_NAME, "rathole");
        }
    }

    #[test]
    fn default_config_is_stable() {
        assert_eq!(default_config(), "rathole/settings/global.toml");
    }

    #[test]
    fn default_bin_points_into_bundle() {
        // 无 RATHOLE_BIN 环境变量时，必须落到 rathole/bin/<os>/ 下。
        let bin = default_bin();
        assert!(bin.starts_with("rathole/bin/"), "unexpected path: {bin}");
        assert!(bin.ends_with(BIN_NAME), "unexpected binary name: {bin}");
    }
}
