//! 远程 SilverBullet 配置。

use std::path::Path;

use crate::error::AppError;

/// 默认的 SB 配置文件名。
pub const SB_ENV_FILE: &str = ".oc-serve-sb.env";

/// 远程 SilverBullet 配置（可热更新）。
#[derive(Debug, Clone, Default)]
pub struct SbConfig {
    pub url: String,
    pub user: String,
    pub password: String,
}

impl SbConfig {
    /// 从环境变量 + `SB_ENV_FILE` 文件加载配置。
    ///
    /// 环境变量优先；缺失时回退到 `SB_ENV_FILE` 文件。
    #[must_use]
    pub fn load() -> Self {
        let mut cfg = Self {
            url: std::env::var("SB_URL").unwrap_or_default(),
            user: std::env::var("SB_USER").unwrap_or_default(),
            password: std::env::var("SB_PASSWORD").unwrap_or_default(),
        };
        let path = Path::new(SB_ENV_FILE);
        if path.is_file()
            && (cfg.url.is_empty() || cfg.user.is_empty() || cfg.password.is_empty())
        {
            if let Ok(contents) = std::fs::read_to_string(path) {
                for line in contents.lines() {
                    let line = line.trim();
                    if line.is_empty() || line.starts_with('#') {
                        continue;
                    }
                    if let Some((k, v)) = line.split_once('=') {
                        let v = v.trim().trim_matches(|c| c == '"' || c == '\'');
                        match k.trim() {
                            "SB_URL" if cfg.url.is_empty() => cfg.url = v.to_string(),
                            "SB_USER" if cfg.user.is_empty() => cfg.user = v.to_string(),
                            "SB_PASSWORD" if cfg.password.is_empty() => {
                                cfg.password = v.to_string()
                            }
                            _ => {}
                        }
                    }
                }
            }
        }
        cfg
    }

    /// 三个字段都非空才算已配置。
    #[must_use]
    pub fn is_configured(&self) -> bool {
        !self.url.is_empty() && !self.user.is_empty() && !self.password.is_empty()
    }

    /// 将配置覆盖写入 `SB_ENV_FILE`（Unix 下 chmod 600）。
    ///
    /// # Errors
    /// 返回 [`AppError::Io`] 当文件写入失败。
    pub fn write_env_file(&self, path: &Path) -> Result<(), AppError> {
        let body = format!(
            "# Generated by `mini-oc-gui-serve` settings\n\
             SB_URL={}\n\
             SB_USER={}\n\
             SB_PASSWORD={}\n",
            self.url, self.user, self.password
        );
        std::fs::write(path, body).map_err(AppError::Io)?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let perms = std::fs::Permissions::from_mode(0o600);
            let _ = std::fs::set_permissions(path, perms);
        }
        Ok(())
    }
}
