//! 远程 SilverBullet 配置 + rathole 内网穿透配置。

use std::path::Path;

use crate::error::AppError;

/// 默认的 SB 配置文件名。
pub const SB_ENV_FILE: &str = ".oc-serve-sb.env";

/// 默认的 Rathole 配置持久化文件名（设置面板热更新）。
pub const RATHOLE_ENV_FILE: &str = ".oc-serve-rathole.env";

/// 生成的 rathole 客户端配置文件（供 rathole 二进制直接使用）。
pub const RATHOLE_CONFIG_FILE: &str = "rathole/settings/global.toml";

/// 远程 SilverBullet 配置（可热更新）。
#[derive(Debug, Clone, Default)]
pub struct SbConfig {
    pub url: String,
    pub user: String,
    pub password: String,
}

impl SbConfig {
    /// 从环境变量 + `SB_ENV_FILE` 文件加载配置。
    ///
    /// 环境变量优先；缺失时回退到 `SB_ENV_FILE` 文件。
    #[must_use]
    pub fn load() -> Self {
        let mut cfg = Self {
            url: std::env::var("SB_URL").unwrap_or_default(),
            user: std::env::var("SB_USER").unwrap_or_default(),
            password: std::env::var("SB_PASSWORD").unwrap_or_default(),
        };
        let path = Path::new(SB_ENV_FILE);
        if path.is_file()
            && (cfg.url.is_empty() || cfg.user.is_empty() || cfg.password.is_empty())
        {
            if let Ok(contents) = std::fs::read_to_string(path) {
                for line in contents.lines() {
                    let line = line.trim();
                    if line.is_empty() || line.starts_with('#') {
                        continue;
                    }
                    if let Some((k, v)) = line.split_once('=') {
                        let v = v.trim().trim_matches(|c| c == '"' || c == '\'');
                        match k.trim() {
                            "SB_URL" if cfg.url.is_empty() => cfg.url = v.to_string(),
                            "SB_USER" if cfg.user.is_empty() => cfg.user = v.to_string(),
                            "SB_PASSWORD" if cfg.password.is_empty() => {
                                cfg.password = v.to_string()
                            }
                            _ => {}
                        }
                    }
                }
            }
        }
        cfg
    }

    /// 三个字段都非空才算已配置。
    #[must_use]
    pub fn is_configured(&self) -> bool {
        !self.url.is_empty() && !self.user.is_empty() && !self.password.is_empty()
    }

    /// 将配置覆盖写入 `SB_ENV_FILE`（Unix 下 chmod 600）。
    ///
    /// # Errors
    /// 返回 [`AppError::Io`] 当文件写入失败。
    pub fn write_env_file(&self, path: &Path) -> Result<(), AppError> {
        let body = format!(
            "# Generated by `mini-oc-gui-serve` settings\n\
             SB_URL={}\n\
             SB_USER={}\n\
             SB_PASSWORD={}\n",
            self.url, self.user, self.password
        );
        std::fs::write(path, body).map_err(AppError::Io)?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let perms = std::fs::Permissions::from_mode(0o600);
            let _ = std::fs::set_permissions(path, perms);
        }
        Ok(())
    }
}

/// rathole 内网穿透的客户端配置（设置面板热更新）。
#[derive(Debug, Clone, Default)]
pub struct RatholeConfig {
    /// 远端服务器 host（对应 `remote_addr` 的主机部分）。
    pub host: String,
    /// 远端服务器端口（对应 `remote_addr` 的端口部分）。
    pub port: String,
    /// 服务名（对应 `client.services.<name>`）。
    pub name: String,
    /// 鉴权 token（对应 `token`）。
    pub token: String,
}

impl RatholeConfig {
    /// 从环境变量 + `RATHOLE_ENV_FILE` 文件加载配置。
    ///
    /// 环境变量优先；缺失时回退到 `RATHOLE_ENV_FILE` 文件。
    #[must_use]
    pub fn load() -> Self {
        let mut cfg = Self {
            host: std::env::var("RATHOLE_HOST").unwrap_or_default(),
            port: std::env::var("RATHOLE_PORT").unwrap_or_default(),
            name: std::env::var("RATHOLE_NAME").unwrap_or_default(),
            token: std::env::var("RATHOLE_TOKEN").unwrap_or_default(),
        };
        let path = Path::new(RATHOLE_ENV_FILE);
        if path.is_file()
            && (cfg.host.is_empty() || cfg.port.is_empty() || cfg.name.is_empty() || cfg.token.is_empty())
        {
            if let Ok(contents) = std::fs::read_to_string(path) {
                for line in contents.lines() {
                    let line = line.trim();
                    if line.is_empty() || line.starts_with('#') {
                        continue;
                    }
                    if let Some((k, v)) = line.split_once('=') {
                        let v = v.trim().trim_matches(|c| c == '"' || c == '\'');
                        match k.trim() {
                            "RATHOLE_HOST" if cfg.host.is_empty() => cfg.host = v.to_string(),
                            "RATHOLE_PORT" if cfg.port.is_empty() => cfg.port = v.to_string(),
                            "RATHOLE_NAME" if cfg.name.is_empty() => cfg.name = v.to_string(),
                            "RATHOLE_TOKEN" if cfg.token.is_empty() => cfg.token = v.to_string(),
                            _ => {}
                        }
                    }
                }
            }
        }
        cfg
    }

    /// 四个字段都非空才算已配置。
    #[must_use]
    pub fn is_configured(&self) -> bool {
        !self.host.is_empty() && !self.port.is_empty() && !self.name.is_empty() && !self.token.is_empty()
    }

    /// 将配置覆盖写入 `RATHOLE_ENV_FILE`（Unix 下 chmod 600）。
    ///
    /// # Errors
    /// 返回 [`AppError::Io`] 当文件写入失败。
    pub fn write_env_file(&self, path: &Path) -> Result<(), AppError> {
        let body = format!(
            "# Generated by `mini-oc-gui-serve` settings\n\
             RATHOLE_HOST={}\n\
             RATHOLE_PORT={}\n\
             RATHOLE_NAME={}\n\
             RATHOLE_TOKEN={}\n",
            self.host, self.port, self.name, self.token
        );
        std::fs::write(path, body).map_err(AppError::Io)?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let perms = std::fs::Permissions::from_mode(0o600);
            let _ = std::fs::set_permissions(path, perms);
        }
        Ok(())
    }

    /// 生成 rathole 客户端配置的 TOML 文本。
    ///
    /// `local_port` 是 rathole 要转发的本地服务端口（即 serve 的启动端口）。
    #[must_use]
    pub fn to_toml(&self, local_port: &str) -> String {
        format!(
            "# global.toml\n\
             [client]\n\
             remote_addr = \"{}:{}\"\n\
             [client.services.{}]\n\
             token = \"{}\"\n\
             local_addr = \"127.0.0.1:{}\"\n",
            self.host, self.port, self.name, self.token, local_port
        )
    }

    /// 将 rathole 客户端配置写入 `RATHOLE_CONFIG_FILE`。
    ///
    /// # Errors
    /// 返回 [`AppError::Io`] 当文件写入失败。
    pub fn write_config_file(&self, path: &Path, local_port: &str) -> Result<(), AppError> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(AppError::Io)?;
        }
        std::fs::write(path, self.to_toml(local_port)).map_err(AppError::Io)
    }
}
