//! Platform + arch-aware resolution of the bundled `rathole` binary + config.
//!
//! `rathole` is a platform-specific native binary (macOS arm64/x86_64,
//! Windows x86_64, Linux x86_64/aarch64, …). The serve binary ships with a
//! `rathole/` directory at the project root that separates binaries per
//! `target_os + target_arch`:
//!
//! ```text
//! rathole/
//! ├── bin/
//! │   ├── macos-aarch64/rathole     # macOS arm64 (Apple Silicon)
//! │   ├── macos-x86_64/rathole      # macOS x86_64 (Intel)
//! │   ├── windows-x86_64/rathole.exe # Windows x86_64
//! │   ├── linux-x86_64/rathole      # Linux x86_64 (gnu)
//! │   └── linux-aarch64/rathole     # Linux aarch64 (gnu)
//! └── settings/*.toml               # tunnel configs (33-/40-/41- prefix)
//! ```
//!
//! # Resolved location
//!
//! After `cargo build`, [`build.rs`](../../build.rs) copies the `rathole/`
//! bundle next to the executable:
//!
//! ```text
//! target/release/
//! ├── mini-oc-gui-serve
//! └── rathole/                                  # copied from source by build.rs
//!     ├── bin/<os>-<arch>/rathole[.exe]
//!     └── settings/*.toml
//! ```
//!
//! At runtime we **prefer** the bundle sitting next to the executable
//! (so a release build is self-contained — no need to ship the source
//! tree or rely on a magic CWD), then fall back to the source-tree
//! layout for `cargo run` / dev workflow, then to CWD-relative.
//!
//! Both defaults can still be overridden at runtime with the
//! `RATHOLE_BIN` / `RATHOLE_CONFIG` environment variables (see
//! [`default_bin`] / [`default_config`]).

/// `<os>-<arch>` bundle subdirectory for the current target.
///
/// 按 Rust 目标三元组对齐 — 同时区分 OS 和 CPU 架构,使同一平台下不同
/// ABI/arch 可以并存多个变体(以后加入 `linux-x86_64-musl`、
/// `macos-x86_64` 等只需扩 match 即可)。
#[cfg(all(target_os = "windows", target_arch = "x86_64"))]
const PLATFORM_DIR: &str = "windows-x86_64";
#[cfg(all(target_os = "windows", target_arch = "aarch64"))]
const PLATFORM_DIR: &str = "windows-aarch64";
#[cfg(all(target_os = "macos", target_arch = "aarch64"))]
const PLATFORM_DIR: &str = "macos-aarch64";
#[cfg(all(target_os = "macos", target_arch = "x86_64"))]
const PLATFORM_DIR: &str = "macos-x86_64";
#[cfg(all(target_os = "linux", target_arch = "x86_64"))]
const PLATFORM_DIR: &str = "linux-x86_64";
#[cfg(all(target_os = "linux", target_arch = "aarch64"))]
const PLATFORM_DIR: &str = "linux-aarch64";
/// 未列出的 OS+arch 组合(罕见 target,如 wasm32-unknown-unknown)。
/// 此时 rathole 没有对应 bundle,运行时找不到属于预期行为。
#[cfg(not(any(
    all(target_os = "windows", target_arch = "x86_64"),
    all(target_os = "windows", target_arch = "aarch64"),
    all(target_os = "macos", target_arch = "aarch64"),
    all(target_os = "macos", target_arch = "x86_64"),
    all(target_os = "linux", target_arch = "x86_64"),
    all(target_os = "linux", target_arch = "aarch64"),
)))]
const PLATFORM_DIR: &str = "unknown";

/// Binary file name on this platform (Windows appends `.exe`).
#[cfg(target_os = "windows")]
const BIN_NAME: &str = "rathole.exe";
#[cfg(not(target_os = "windows"))]
const BIN_NAME: &str = "rathole";

/// Default tunnel config (generated by the settings panel, see
/// [`crate::config::RATHOLE_CONFIG_FILE`]).
const DEFAULT_CONFIG: &str = crate::config::RATHOLE_CONFIG_FILE;

/// Resolve the rathole binary path for the current platform.
///
/// Precedence:
/// 1. `RATHOLE_BIN` env var (absolute or CWD-relative, used verbatim).
/// 2. `<exe_dir>/rathole/bin/<os>/<binary>` — bundle that
///    [`build.rs`](../../build.rs) copies next to the executable on every
///    `cargo build`. Works whether the binary lives in `target/release/`,
///    `target/debug/`, or any deployment directory.
/// 3. `rathole/bin/<os>/<binary>` relative to the CWD (source-tree dev).
/// 4. Walk upward from the executable for `rathole/bin/<os>/<binary>`
///    (covers legacy layouts where the bundle lives outside `target/`).
#[must_use]
pub fn default_bin() -> String {
    if let Ok(v) = std::env::var("RATHOLE_BIN") {
        return v;
    }
    let rel = format!("rathole/bin/{PLATFORM_DIR}/{BIN_NAME}");

    // 2. exe-adjacent bundle (preferred for release builds)
    if let Some(exe_dir) = exe_dir() {
        let candidate = exe_dir.join(&rel);
        if candidate.exists() {
            return candidate.to_string_lossy().into_owned();
        }
    }
    // 3. CWD-relative (dev workflow)
    resolve_bundled(&rel)
}

/// Resolve the rathole tunnel config path.
///
/// Precedence:
/// 1. `RATHOLE_CONFIG` env var.
/// 2. `<exe_dir>/rathole/settings/global.toml` (release bundle).
/// 3. CWD-relative or upward search (dev / source-tree workflow).
#[must_use]
pub fn default_config() -> String {
    if let Ok(v) = std::env::var("RATHOLE_CONFIG") {
        return v;
    }
    // 2. exe-adjacent bundle (preferred for release builds)
    if let Some(exe_dir) = exe_dir() {
        let candidate = exe_dir.join(DEFAULT_CONFIG);
        if candidate.exists() {
            return candidate.to_string_lossy().into_owned();
        }
    }
    // 3. CWD / upward (dev / source-tree workflow)
    resolve_bundled(DEFAULT_CONFIG)
}

/// Parent directory of the running executable, or `None` if unavailable.
fn exe_dir() -> Option<std::path::PathBuf> {
    std::env::current_exe()
        .ok()
        .and_then(|p| p.parent().map(|d| d.to_path_buf()))
}

/// Locate a bundled file first relative to the CWD, then by walking up from
/// the running executable's directory. Falls back to the CWD-relative path
/// (so the caller can report a meaningful "not found" error later).
fn resolve_bundled(relative: &str) -> String {
    if std::path::Path::new(relative).exists() {
        return relative.to_string();
    }
    if let Some(exe_dir) = exe_dir() {
        for ancestor in exe_dir.ancestors().take(5) {
            let candidate = ancestor.join(relative);
            if candidate.exists() {
                return candidate.to_string_lossy().into_owned();
            }
        }
    }
    relative.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bin_name_matches_platform() {
        if cfg!(target_os = "windows") {
            assert_eq!(BIN_NAME, "rathole.exe");
        } else {
            assert_eq!(BIN_NAME, "rathole");
        }
    }

    #[test]
    fn platform_dir_includes_arch() {
        // bundle 路径必须 `<os>-<arch>` 复合,而不是单纯的 `<os>` —
        // 这样同一平台下不同 ABI(arm64 vs x86_64)能并存。
        assert!(
            PLATFORM_DIR.contains('-'),
            "PLATFORM_DIR should be <os>-<arch>, got: {PLATFORM_DIR}"
        );
        assert_ne!(
            PLATFORM_DIR, "unknown",
            "current target must be in the supported os-arch list"
        );
    }

    #[test]
    fn default_config_is_stable() {
        assert_eq!(default_config(), "rathole/settings/global.toml");
    }

    #[test]
    fn default_bin_falls_back_to_relative_path() {
        // 即便 exe 旁没有 bundle,也不应 panic —— 至少返回一个可读的相对路径。
        // (具体是否真存在取决于运行环境;此处只断言返回值符合预期格式。)
        let bin = default_bin();
        assert!(
            bin.ends_with(BIN_NAME),
            "rathole binary path should end with {BIN_NAME}, got: {bin}"
        );
    }

    #[test]
    fn default_bin_path_uses_platform_dir() {
        // `default_bin` 应总是包含 `<os>-<arch>` 子目录(无论最终是 exe 旁的绝对路径
        // 还是 CWD 兜底的相对路径)。
        let bin = default_bin();
        assert!(
            bin.contains(PLATFORM_DIR),
            "default_bin should include PLATFORM_DIR={PLATFORM_DIR}, got: {bin}"
        );
    }
}